apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  labels:
    app: parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: "80,443,4222"
        config.linkerd.io/proxy-cpu-request: 4m
        config.linkerd.io/proxy-memory-request: 10Mi
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: parser
          image: busybox
          command:
            - /app/servicebin
          livenessProbe:
            exec:
              command:
                - /app/grpc_health_probe
                - -addr=:8080
          readinessProbe:
            exec:
              command:
                - /app/grpc_health_probe
                - -addr=:8080
          ports:
            - containerPort: 8080
              name: grpc
              protocol: TCP
            - containerPort: 8888
              name: pprof
              protocol: TCP
          resources:
            requests:
              cpu: 97m
              memory: 318Mi
            limits:
              cpu: "1.5"
              memory: 1.5Gi
          env:
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: grpc
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: redis
            - name: STAN_CLUSTERID
              valueFrom:
                configMapKeyRef:
                  key: clusterid
                  name: stan
            - name: STAN_URLMAXINFLIGHT
              valueFrom:
                configMapKeyRef:
                  key: urlmaxinflight
                  name: stan
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: nats
            - name: STAN_SUBJECTREVIEWMODERATION
              valueFrom:
                configMapKeyRef:
                  key: subjectreviewmoderation
                  name: stan
            - name: STAN_SUBJECTURL
              valueFrom:
                configMapKeyRef:
                  key: subjecturl
                  name: stan
            - name: STAN_SUBJECTCOMPANYNEW
              valueFrom:
                configMapKeyRef:
                  key: subjectcompanynew
                  name: stan
            - name: STAN_SUBJECTANALYZERESULT
              valueFrom:
                configMapKeyRef:
                  key: subjectanalyzeresult
                  name: stan
            - name: STAN_SUBJECTIMAGEUPLOADRESULT
              valueFrom:
                configMapKeyRef:
                  key: subjectimageuploadresult
                  name: stan
            - name: STAN_SUBJECTDELETEIMAGE
              valueFrom:
                configMapKeyRef:
                  key: subjectdeleteimage
                  name: stan
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: mongodb
            - name: VK_USERTOKENS
              valueFrom:
                secretKeyRef:
                  key: usertokens
                  name: vk
            - name: S3_DOWNLOADBUCKETNAME
              valueFrom:
                configMapKeyRef:
                  key: downloadbucketname
                  name: s3
            - name: S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: endpoint
                  name: s3
            - name: S3_ACCESSKEYID
              valueFrom:
                configMapKeyRef:
                  key: accesskeyid
                  name: s3
            - name: S3_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: secretaccesskey
                  name: s3
            - name: S3_SECURE
              valueFrom:
                configMapKeyRef:
                  key: secure
                  name: s3
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: region
                  name: s3
            - name: SERVICE_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: image
                  name: service
            - name: SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  key: user
                  name: service
            - name: SERVICE_CLASSIFIER
              valueFrom:
                configMapKeyRef:
                  key: classifier
                  name: service
            - name: SERVICE_WAPPALYZER
              valueFrom:
                configMapKeyRef:
                  key: wappalyzer
                  name: service
            - name: LOGLEVEL
              value: error

---
apiVersion: v1
kind: Service
metadata:
  name: parser
  labels:
    app: parser
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: parser
